baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Wooderful Carpentry'

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
